### ISSUE TITLE
NoSuchMethodError SMIMESignedGenerator.generate

### ISSUE THREAD

**Issue by MakakWasTaken** [simple-java-mail/java-utils-mail-smime#4]
I am currently trying to implement this library with my implementation of Jakarta Mail `2.0.1`

When I try to use the example code and sign a message as the following:
```java
    private static MimeMessage signMessage(Session session, MimeMessage message) throws Exception {
        SmimeKey smimeKey = getSmimeKey();
        return SmimeUtil.sign(session, message, smimeKey);
    }
```

I have also tried to generate to use the SmimeUtil.sign with a `MimeBodyPart` as the argument, this did nothing aswell.  

I get an error stating:
```
java.lang.NoSuchMethodError: 'jakarta.mail.internet.MimeMultipart org.bouncycastle.mail.smime.SMIMESignedGenerator.generate(jakarta.mail.internet.MimeBodyPart)'

	at org.simplejavamail.utils.mail.smime.SmimeUtil.sign(SmimeUtil.java:314)
	at org.simplejavamail.utils.mail.smime.SmimeUtil.sign(SmimeUtil.java:404)
	at org.simplejavamail.utils.mail.smime.SmimeUtil.sign(SmimeUtil.java:398)
```

The versions I am using are as the following:
```xml
    <dependency>
      <groupId>com.sun.mail</groupId>
      <artifactId>jakarta.mail</artifactId>
      <version>2.0.1</version>
    </dependency>
    <dependency>
      <groupId>com.sun.activation</groupId>
      <artifactId>jakarta.activation</artifactId>
      <version>2.0.1</version>
    </dependency>
    <dependency>
      <groupId>org.simplejavamail</groupId>
      <artifactId>utils-mail-smime</artifactId>
      <version>2.0.1</version>
    </dependency>
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcjmail-jdk15to18</artifactId>
      <version>1.70</version>
    </dependency>
```

**Comment by bbottema** [comment]
Can you do a _mvn dependency:tree_ and see what the actual dependencies resolve to in runtime?

**Comment by MakakWasTaken** [comment]
Sorry for the late response, but I have not had the time to look at it since. 

I have tried to look at the dependency tree but could not find anything wrong with the version:

```
 ] |  |  \- org.springframework:spring-jcl:jar:5.3.20:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.30:compile:5.3.20:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.7.0:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.7.0:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.13.3:compile
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.3:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.13.3:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.13.3:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.3:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.13.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.7.0:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.63:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.63:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.63:compile
[INFO] |  +- org.springframework:spring-web:jar:5.3.20:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:5.3.20:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.3.20:compile
[INFO] |     +- org.springframework:spring-aop:jar:5.3.20:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.3.20:compile
[INFO] +- com.helger.phase4:phase4-lib:jar:1.3.9:compile
[INFO] |  +- org.bouncycastle:bcmail-jdk15on:jar:1.70:compile
[INFO] |  |  +- org.bouncycastle:bcprov-jdk15on:jar:1.70:compile
[INFO] |  |  +- org.bouncycastle:bcutil-jdk15on:jar:1.70:compile
[INFO] |  |  \- org.bouncycastle:bcpkix-jdk15on:jar:1.70:compile
[INFO] |  +- org.apache.wss4j:wss4j-ws-security-dom:jar:2.4.1:compile
[INFO] |  |  +- org.apache.wss4j:wss4j-ws-security-common:jar:2.4.1:compile
[INFO] |  |  |  +- org.apache.santuario:xmlsec:jar:2.3.0:compile
[INFO] |  |  |  +- org.cryptacular:cryptacular:jar:1.2.4:compile
[INFO] |  |  |  +- joda-time:joda-time:jar:2.10.10:compile
[INFO] |  |  |  \- org.jasypt:jasypt:jar:1.9.3:compile
[INFO] |  |  \- jakarta.xml.ws:jakarta.xml.ws-api:jar:2.3.3:compile
[INFO] |  |     +- jakarta.xml.soap:jakarta.xml.soap-api:jar:1.4.2:compile
[INFO] |  |     \- jakarta.jws:jakarta.jws-api:jar:2.1.0:runtime
[INFO] |  +- com.helger.commons:ph-commons:jar:10.1.6:compile
[INFO] |  |  \- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- com.helger.commons:ph-xml:jar:10.1.6:compile
[INFO] |  +- com.helger.commons:ph-jaxb:jar:10.1.6:compile
[INFO] |  +- com.helger.commons:ph-jaxb-adapter:jar:10.1.6:compile
[INFO] |  +- com.helger.commons:ph-datetime:jar:10.1.6:compile
[INFO] |  +- com.helger.commons:ph-bc:jar:10.1.6:compile
[INFO] |  +- com.helger.commons:ph-scopes:jar:10.1.6:compile
[INFO] |  +- com.helger.commons:ph-json:jar:10.1.6:compile
[INFO] |  +- com.helger.web:ph-mail:jar:9.6.4:compile
[INFO] |  +- com.helger.web:ph-http:jar:9.6.4:compile
[INFO] |  |  +- com.helger.web:ph-network:jar:9.6.4:compile
[INFO] |  |  \- com.helger.commons:ph-security:jar:10.1.6:compile
[INFO] |  +- com.helger.web:ph-httpclient:jar:9.6.4:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
[INFO] |  |  |  \- commons-codec:commons-codec:jar:1.11:compile
[INFO] |  |  \- org.slf4j:jcl-over-slf4j:jar:1.7.32:compile
[INFO] |  +- com.helger.xsd:ph-xsds-xmldsig:jar:2.6.0:compile
[INFO] |  +- com.helger.xsd:ph-xsds-xlink:jar:2.6.0:compile
[INFO] |  |  \- com.helger.xsd:ph-xsds-xml:jar:2.6.0:compile
[INFO] |  +- com.helger.masterdata:ph-tenancy:jar:6.2.4:compile
[INFO] |  |  \- com.helger.masterdata:ph-masterdata:jar:6.2.4:compile
[INFO] |  +- com.helger.commons:ph-config:jar:10.1.6:compile
[INFO] |  +- com.helger.photon:ph-oton-app:jar:8.4.0:compile
[INFO] |  |  +- com.helger.commons:ph-collection:jar:10.1.6:compile
[INFO] |  |  +- com.helger.commons:ph-dao:jar:10.1.6:compile
[INFO] |  |  +- com.helger.web:ph-servlet:jar:9.6.3:compile
[INFO] |  |  +- com.helger.web:ph-useragent:jar:9.6.3:compile
[INFO] |  |  +- com.helger:ph-css:jar:6.5.0:compile
[INFO] |  |  \- com.helger.photon:ph-oton-html:jar:8.4.0:compile
[INFO] |  +- com.helger.photon:ph-oton-audit:jar:8.4.0:compile
[INFO] |  +- com.helger.photon:ph-oton-security:jar:8.4.0:compile
[INFO] |  +- com.helger.schedule:ph-schedule:jar:4.2.0:compile
[INFO] |  |  \- com.helger.schedule:ph-mini-quartz:jar:4.2.0:compile
[INFO] |  +- com.helger.web:ph-web:jar:9.6.4:compile
[INFO] |  +- com.helger.web:ph-xservlet:jar:9.6.4:compile
[INFO] |  \- org.slf4j:jul-to-slf4j:jar:1.7.32:compile
[INFO] +- com.helger.phase4:phase4-profile-entsog:jar:1.3.9:compile
[INFO] +- com.sun.mail:jakarta.mail:jar:2.0.1:compile
[INFO] +- com.sun.activation:jakarta.activation:jar:2.0.1:compile
[INFO] +- com.sun.mail:javax.mail:jar:1.6.2:compile
[INFO] |  \- javax.activation:activation:jar:1.1:compile
[INFO] +- org.simplejavamail:simple-java-mail:jar:7.1.1:compile
[INFO] |  +- org.simplejavamail:core-module:jar:7.1.1:compile
[INFO] |  |  \- com.sanctionco.jmail:jmail:jar:1.2.1:compile
[INFO] |  +- com.github.bbottema:jetbrains-runtime-annotations:jar:1.0.1:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.32:compile
**
[INFO] +- org.simplejavamail:smime-module:jar:7.1.1:compile
[INFO] |  \- org.simplejavamail:utils-mail-smime:jar:2.0.1:compile
[INFO] |     \- org.bouncycastle:bcjmail-jdk15to18:jar:1.70:compile
[INFO] |        +- org.bouncycastle:bcprov-jdk15to18:jar:1.70:compile
[INFO] |        +- org.bouncycastle:bcutil-jdk15to18:jar:1.70:compile
[INFO] |        +- org.bouncycastle:bcpkix-jdk15to18:jar:1.70:compile
[INFO] |        +- jakarta.mail:jakarta.mail-api:jar:2.1.0:compile (version selected from constraint [2.0,3.0))
[INFO] |        \- jakarta.activation:jakarta.activation-api:jar:2.1.0:compile (version selected from constraint [2.0,3.0))
**
```

The relevant part is marked by **

Please note that since my last post I have changed the dependencies to:
```
    <dependency>
      <groupId>com.sun.mail</groupId>
      <artifactId>jakarta.mail</artifactId>
      <version>2.0.1</version>
    </dependency>
    <dependency>
      <groupId>com.sun.activation</groupId>
      <artifactId>jakarta.activation</artifactId>
      <version>2.0.1</version>
    </dependency>
    <dependency>
      <groupId>com.sun.mail</groupId>
      <artifactId>javax.mail</artifactId>
      <version>1.6.2</version>
    </dependency>
    <dependency>
      <groupId>org.simplejavamail</groupId>
      <artifactId>simple-java-mail</artifactId>
      <version>7.1.1</version>
    </dependency>
    <dependency>
      <groupId>org.simplejavamail</groupId>
      <artifactId>smime-module</artifactId>
      <version>7.1.1</version>
    </dependency>
```

As far as I understand this **smime-module** resolves to this module.

**Comment by MakakWasTaken** [comment]
I found the solution to downgrade to simplemail 6.x.x because it uses JavaMail instead of Jakarta
